// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Frame) DeepCopyInto(out *Frame) {
	*out = *in
	in.Action.DeepCopyInto(&out.Action)
	if in.CausedBy != nil {
		in, out := &in.CausedBy, &out.CausedBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Props != nil {
		in, out := &in.Props, &out.Props
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Frame.
func (in *Frame) DeepCopy() *Frame {
	if in == nil {
		return nil
	}
	out := new(Frame)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrameState) DeepCopyInto(out *FrameState) {
	*out = *in
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new(FrameStateRunning)
		(*in).DeepCopyInto(*out)
	}
	if in.Finished != nil {
		in, out := &in.Finished, &out.Finished
		*out = new(FrameStateFinished)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrameState.
func (in *FrameState) DeepCopy() *FrameState {
	if in == nil {
		return nil
	}
	out := new(FrameState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrameStateFinished) DeepCopyInto(out *FrameStateFinished) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.FinishedAt.DeepCopyInto(&out.FinishedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrameStateFinished.
func (in *FrameStateFinished) DeepCopy() *FrameStateFinished {
	if in == nil {
		return nil
	}
	out := new(FrameStateFinished)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrameStateRunning) DeepCopyInto(out *FrameStateRunning) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrameStateRunning.
func (in *FrameStateRunning) DeepCopy() *FrameStateRunning {
	if in == nil {
		return nil
	}
	out := new(FrameStateRunning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrameStatus) DeepCopyInto(out *FrameStatus) {
	*out = *in
	in.State.DeepCopyInto(&out.State)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrameStatus.
func (in *FrameStatus) DeepCopy() *FrameStatus {
	if in == nil {
		return nil
	}
	out := new(FrameStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Movie) DeepCopyInto(out *Movie) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Movie.
func (in *Movie) DeepCopy() *Movie {
	if in == nil {
		return nil
	}
	out := new(Movie)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Movie) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MovieList) DeepCopyInto(out *MovieList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Movie, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MovieList.
func (in *MovieList) DeepCopy() *MovieList {
	if in == nil {
		return nil
	}
	out := new(MovieList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MovieList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MovieSpec) DeepCopyInto(out *MovieSpec) {
	*out = *in
	if in.Props != nil {
		in, out := &in.Props, &out.Props
		*out = make([]Prop, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Frames != nil {
		in, out := &in.Frames, &out.Frames
		*out = make([]Frame, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MovieSpec.
func (in *MovieSpec) DeepCopy() *MovieSpec {
	if in == nil {
		return nil
	}
	out := new(MovieSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MovieStatus) DeepCopyInto(out *MovieStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FrameStatuses != nil {
		in, out := &in.FrameStatuses, &out.FrameStatuses
		*out = make([]FrameStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MovieStatus.
func (in *MovieStatus) DeepCopy() *MovieStatus {
	if in == nil {
		return nil
	}
	out := new(MovieStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Prop) DeepCopyInto(out *Prop) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Prop.
func (in *Prop) DeepCopy() *Prop {
	if in == nil {
		return nil
	}
	out := new(Prop)
	in.DeepCopyInto(out)
	return out
}
