# permissions for end users to view movies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: movie-viewer-role
rules:
  - apiGroups:
      - director.kuberik.io
    resources:
      - movies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - director.kuberik.io
    resources:
      - movies/status
    verbs:
      - get
