
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - director.kuberik.io
  resources:
  - movies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - director.kuberik.io
  resources:
  - movies/finalizers
  verbs:
  - update
- apiGroups:
  - director.kuberik.io
  resources:
  - movies/status
  verbs:
  - get
  - patch
  - update
