---
apiVersion: director.kuberik.io/v1
kind: Movie
metadata:
  name: movie-sample
spec:
  frames:
    - name: clone
      action:
        template:
          spec:
            containers:
              - name: clone
                image: alpine:latest
                command: [bash, -c]
                args: ["echo cloning... && sleep 5"]
    - name: build
      causedBy:
        - clone
      action:
        template:
          spec:
            containers:
              - name: build
                image: alpine:latest
                command: [bash, -c]
                args: ["echo building... && sleep 5"]
